src/Entity/Etapes.php
<?php

namespace App\Entity;

use App\Repository\EtapesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtapesRepository::class)]
class Etapes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $et_numero = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $et_description = null;

    #[ORM\OneToMany(mappedBy: 'etapes', targetEntity: Quantites::class, cascade: ["remove"])]
    private Collection $quantites;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Cuisson $cuisson = null;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recettes $recette = null;

    public function __construct()
    {
        $this->quantites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtNumero(): ?int
    {
        return $this->et_numero;
    }

    public function setEtNumero(int $et_numero): static
    {
        $this->et_numero = $et_numero;

        return $this;
    }

    public function getEtDescription(): ?string
    {
        return $this->et_description;
    }

    public function setEtDescription(string $et_description): static
    {
        $this->et_description = $et_description;

        return $this;
    }

    /**
     * @return Collection<int, Quantites>
     */
    public function getQuantites(): Collection
    {
        return $this->quantites;
    }

    public function addQuantite(Quantites $quantite): static
    {
        if (!$this->quantites->contains($quantite)) {
            $this->quantites->add($quantite);
            $quantite->setEtapes($this);
        }

        return $this;
    }

    public function removeQuantite(Quantites $quantite): static
    {
        if ($this->quantites->removeElement($quantite)) {
            // set the owning side to null (unless already changed)
            if ($quantite->getEtapes() === $this) {
                $quantite->setEtapes(null);
            }
        }

        return $this;
    }

    public function getCuisson(): ?Cuisson
    {
        return $this->cuisson;
    }

    public function setCuisson(?Cuisson $cuisson): static
    {
        $this->cuisson = $cuisson;

        return $this;
    }

    public function getRecette(): ?Recettes
    {
        return $this->recette;
    }

    public function setRecette(?Recettes $recette): static
    {
        $this->recette = $recette;

        return $this;
    }
}

src/Entity/Recettes.php
<?php

namespace App\Entity;

use App\Repository\RecettesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: RecettesRepository::class)]
#[UniqueEntity(fields: ['re_libelle'], message: 'Une recette avec ce nom existe déjà.')]
#[Vich\Uploadable]
class Recettes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $re_libelle = null;

    #[Vich\UploadableField(mapping: 'recettes_images', fileNameProperty: 're_image')]   
    private ?File $imageFile = null;
    
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $re_image = null;

    #[ORM\Column(nullable: true)]
    private ?int $re_nb_personnes = null;

    #[ORM\Column(nullable: true)]
    private ?int $re_temps = null;

    #[ORM\Column(nullable: true)]
    private ?int $re_kcal = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $re_commentaires = null;

    #[ORM\ManyToOne(inversedBy: 'recettes')]
    private ?Regions $regions = null;

    #[ORM\OneToMany(mappedBy: 'recette', targetEntity: Etapes::class, cascade: ["remove"])]
    #[ORM\OrderBy(['et_numero' => 'ASC'])]
    private Collection $etapes;

    #[ORM\ManyToMany(targetEntity: Tags::class, inversedBy: 'recettes')]
    private Collection $recette_tags;

    #[ORM\ManyToMany(targetEntity: Utilisateurs::class, inversedBy: 'recettes')]
    private Collection $recettes_utilisateurs;

    public function __construct()
    {
        $this->etapes = new ArrayCollection();
        $this->recette_tags = new ArrayCollection();
        $this->recettes_utilisateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReLibelle(): ?string
    {
        return $this->re_libelle;
    }

    public function setReLibelle(string $re_libelle): static
    {
        $this->re_libelle = $re_libelle;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;

        return $this;
    }

    public function getReImage(): ?string
    {
        return $this->re_image;
    }

    public function setReImage(?string $re_image): static
    {
        $this->re_image = $re_image;

        return $this;
    }

    public function getReNbPersonnes(): ?int
    {
        return $this->re_nb_personnes;
    }

    public function setReNbPersonnes(int $re_nb_personnes): static
    {
        $this->re_nb_personnes = $re_nb_personnes;

        return $this;
    }

    public function getReTemps(): ?int
    {
        return $this->re_temps;
    }

    public function setReTemps(?int $re_temps): static
    {
        $this->re_temps = $re_temps;

        return $this;
    }

    public function getReKcal(): ?int
    {
        return $this->re_kcal;
    }

    public function setReKcal(?int $re_kcal): static
    {
        $this->re_kcal = $re_kcal;

        return $this;
    }

    public function getReCommentaires(): ?string
    {
        return $this->re_commentaires;
    }

    public function setReCommentaires(?string $re_commentaires): static
    {
        $this->re_commentaires = $re_commentaires;

        return $this;
    }

    public function getRegions(): ?Regions
    {
        return $this->regions;
    }

    public function setRegions(?Regions $regions): static
    {
        $this->regions = $regions;

        return $this;
    }

    /**
     * @return Collection<int, Etapes>
     */
    public function getEtapes(): Collection
    {
        return $this->etapes;
    }

    public function addEtape(Etapes $etape): static
    {
        if (!$this->etapes->contains($etape)) {
            $this->etapes->add($etape);
            $etape->setRecette($this);
        }

        return $this;
    }

    public function removeEtape(Etapes $etape): static
    {
        if ($this->etapes->removeElement($etape)) {
            // set the owning side to null (unless already changed)
            if ($etape->getRecette() === $this) {
                $etape->setRecette(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tags>
     */
    public function getRecetteTags(): Collection
    {
        return $this->recette_tags;
    }

    public function addRecetteTag(Tags $recetteTag): static
    {
        if (!$this->recette_tags->contains($recetteTag)) {
            $this->recette_tags->add($recetteTag);
        }

        return $this;
    }

    public function removeRecetteTag(Tags $recetteTag): static
    {
        $this->recette_tags->removeElement($recetteTag);

        return $this;
    }

    /**
     * @return Collection<int, Utilisateurs>
     */
    public function getRecettesUtilisateurs(): Collection
    {
        return $this->recettes_utilisateurs;
    }

    public function addRecettesUtilisateur(Utilisateurs $recettesUtilisateur): static
    {
        if (!$this->recettes_utilisateurs->contains($recettesUtilisateur)) {
            $this->recettes_utilisateurs->add($recettesUtilisateur);
        }

        return $this;
    }

    public function removeRecettesUtilisateur(Utilisateurs $recettesUtilisateur): static
    {
        $this->recettes_utilisateurs->removeElement($recettesUtilisateur);

        return $this;
    }
}

src/Form/EtapesType.php
<?php

namespace App\Form;

use App\Entity\Cuisson;
use App\Entity\Etapes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtapesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('et_numero', IntegerType::class, [ 
                'label' => 'Etapes numero:'  ,
                'label_attr' => ['class' => 'form-label'],
            ])

            ->add('et_description' , TextareaType::class, [ 
                'label' => 'Desciption de l\'étape*  '  ,
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['placeholder' => 'Insérer la description de l\'étape']
            ])

            ->add('cuisson', EntityType::class, [
                'class' => Cuisson::class,
                'required' => false,
                'placeholder' => '',
                'choice_label' => 'cu_libelle',
                'label_attr' => ['class' => 'form-label'],
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Valider',
                'attr' => ['class' => 'btn']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etapes::class,
        ]);
    }
}

src/Controller/EtapesController.php
<?php

namespace App\Controller;

use App\Entity\Etapes;
use App\Entity\Recettes;
use App\Form\EtapesType;
use App\Repository\EtapesRepository;
use App\Repository\RecettesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EtapesController extends AbstractController
{
    #[Route('/Create_etapes/{id}', name: 'Create_etapes')]
    public function Create(EtapesRepository $repo,RecettesRepository $repoRecettes, Request $request, EntityManagerInterface $manager, $id): Response
    {
        $recettes = $repoRecettes->findAllSortedByName(); 

        $etape = new Etapes();
        $etapes = $repo->findAll();
        $form = $this->createForm(EtapesType::class, $etape);
        $form->handleRequest($request);
        $recette = $manager->getRepository(Recettes::class)->find($id);
        $recetteId = $request->get('id');
        


    if ($form->isSubmitted() && $form->isValid()) {
        $etape = $form->getData();        
        $etape->setRecette($recette);
        $manager->persist($etape);
        $manager->flush();
        return $this->redirectToRoute('Create_Qantites', [
            'etapeId' => $etape->getId(),
            'recetteId' => $recetteId,
        ]);
    }
    return $this->render('etapes/Create_Etape.html.twig', [
        'recettes' => $recettes,
        'etapes' => $etapes,
        'form' => $form,
        'message' => 'Ajouter une Etape',
        'recette' => $recette, 
        ]);
    }

    #[Route('etapes/update/{etapeId}/{recetteId}', name: 'etapes_update')]
    public function update(Etapes $etape,EtapesRepository $etapesRepository, RecettesRepository $repoRecettes,Recettes $recettes, Request $request,EntityManagerInterface $manager,$etapeId,$recetteId): Response 
    {
                //--------- RECETTE DETAIL --------
                $ingredientsAggreges = [];

                foreach ($recettes->getEtapes() as $etape) {
                    foreach ($etape->getQuantites() as $quantite) {
                        $produit = $quantite->getProduits();
                        $unite = $quantite->getUnites();
                        $nomIngredient = $produit ? $produit->getPRLIBELLE() : '';
                        if (!$produit && !$nomIngredient) {
                            continue;
                        }
        
                        if (!array_key_exists($nomIngredient, $ingredientsAggreges)) {
                            $ingredientsAggreges[$nomIngredient] = [
                                'quantite' => 0,
                                'unite' => $unite ? $unite->getUnLibelle() : ''
                            ];
                        }
                        $ingredientsAggreges[$nomIngredient]['quantite'] += $quantite->getQuQuantites() ?? '';
                    }
                }
                $etapes = $etapesRepository->findAll();
                $form = $this->createForm(EtapesType::class, $etape);
        $form->handleRequest($request);
    
        // Ici, nous utilisons directement $recetteId passé à la méthode.
        $recette = $manager->getRepository(Recettes::class)->find($recetteId);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($etape);
            $manager->flush();
    
            return $this->redirectToRoute('Update_Quantites', [
                'etapeId' => $etape->getId(),
                'recetteId' => $recetteId,
            ]);
        }
    
        return $this->render('etapes/Etape_Update.html.twig', [
            'recette' => $recette, // Assurez-vous que c'est le nom correct de la variable attendue dans le template.
            'etape' => $etape, // Ici, 'etapes' a été changé en 'etape' pour correspondre à la variable que vous avez déclarée.
            'etapes' => $etapes, // Ici, 'etapes' a été changé en 'etape' pour correspondre à la variable que vous avez déclarée.
            'form' => $form, // Assurez-vous de passer createView() pour le formulaire.
            'message' => 'Modifier une étape',
            'ingredientsAggreges' => $ingredientsAggreges,
        ]);
    }
    // public function update(Etapes $etape,RecettesRepository $repoRecettes, Request $request, EntityManagerInterface $manager, $etapeId, $recetteId): Response
    // {        
    //         $form = $this->createForm(EtapesType::class, $etape);
    //         $form->handleRequest($request);
    //         $recette = $manager->getRepository(Recettes::class)->find($recetteId);
    //         $recetteId = $request->get('id');
    
    //         if($form->isSubmitted() && $form->isValid()) {
    //             $etape = $form->getData();
    //             $recette = $manager->getRepository(Recettes::class)->find($recetteId);
    //             $etape->setRecette($recette);
    //             $manager->persist($etape);
    //             $manager->flush();
    //             return $this->redirectToRoute('Update_Qantites', [
    //                 'etapeId' => $etape->getId(),
    //                 'recetteId' => $recetteId,
    //             ]);
    //                 }

    //         return $this->render('etapes/Etape_Update.html.twig', [
    //             'recettes' => $recette,
    //             'etapes' => $etape,
    //             'form' => $form,
    //             'message' => 'Modifier une étape',
    //             'etapeId' => $etape->getId(),
    //             'recetteId' => $recetteId,
                
    //         ]);
    //     }


}

templates/etapes/Create_Etape.html.twig
{# ***************************************** FICHIER PARENT ******************************* #}

{% extends 'backOffice.html.twig' %}

{# ***************************************** TITLE **************************************** #}

{% block title %}Ajout Etape{% endblock %}

{# ***************************************** NAV ET MENU ********************************** #}

{% block menu %}
    {% include 'recettes/gestionRecettte.html.twig' %}
{% endblock %}

{# ***************************************** BODY ***************************************** #}

{% block body %}

{# **************** gestion d ela bibliothèque select2 pour l'input select ***************** #}

    <!-- Inclusion de jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Inclusion de Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <script>
    $(document).ready(function() {

    $(".js-example-theme-multiple").select2({
    theme: "classic"
    });});
    </script>


{# ----------------------------------- ADD ETAPE --------------------------------------------------- #}
    <div id='container_form' class='ma-classe'>
        <form method="post" enctype="multipart/form-data" class='popupEtape'>
            <div class='popUP_Create add-mode '>
                <div class='col-lg-3 Create add-mode '> 
                    {# Icon add #}
                    <i class="fa-regular fa-square-plus fa-5x changeColor"></i>
                    {# <i class="fa-regular fa-square-plus fa-5x changeColor"></i> #}
                </div>

                <div class='d-flex align-items-center'>
                    {# titre Create de la pop up ajouter #}
                    <h4>CREATE ETAPE</h4>
                </div>  
            </div>
            <div>
                <h5 class='text-center mt-4 mb-4 text_Size'>Recette <span class="form-contro text_color" >{{ recette.reLibelle }}</span></h5>
            </div>

            <div class='d-flex col-12 mt-2'>
                <div class='col-lg-6'>
                    <div class='p-0' >
                        <div>
                            <label for="{{ form.et_numero.vars.id }}" class="form-contro">Numero de l'étape*</label>
                            {{ form_widget(form.et_numero, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                </div>

                <div class='col-lg-6'>
                    <div class='p-0' >
                        <div>
                            <label for="{{ form.cuisson.vars.id }}" class="form-contro">Mode de cuisson</label>
                            {{ form_widget(form.cuisson, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                </div>
            </div>


            <div class='d-flex col-12 mt-2' >
                <div class='col-lg-12' >
                    <label for="{{ form.et_description.vars.id }}" class="form-contro">Description de l'étape*</label>
                    {{ form_widget(form.et_description, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>

            <div class='SubmitRecettes'> 
                {# Boutton Submit pour soumettre la nouvelle Etape #}
                {{ form_widget(form.submit , {'attr': {'class': 'btn myBouttonSubmit  m-2'}}) }}
            </div>

            {{ form_rest(form) }}
        </form>
    </div> 

    <script>
        console.log("Avant l'ajout de la classe");
window.onload = function() {  
    var element = document.querySelector('.ma-classe'); 
  console.log("Élément trouvé :", element);

  if (element) {
    document.body.classList.add('scroll-desactive');
    $('.voile').toggle(); 
    console.log("Classe ajoutée");
  } else {
    console.log("Élément avec la classe spécifique non trouvé");
  }
};
console.log("Après l'écouteur d'événements");    </script>

    </script>
    {% endblock %}

templates/etapes/Etape_Update.html.twig
{# ***************************************** FICHIER PARENT ******************************* #}

{% extends 'backOffice.html.twig' %}

{# ***************************************** TITLE **************************************** #}

{% block title %}Ajout Etape{% endblock %}

{# ***************************************** NAV ET MENU ********************************** #}

{% block menu %}
	{% include 'recettes/update_recette.html.twig' %}
{% endblock %}

{# ***************************************** BODY ***************************************** #}

{% block body %}

{# **************** gestion d ela bibliothèque select2 pour l'input select ***************** #}

    <!-- Inclusion de jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Inclusion de Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <script>
    $(document).ready(function() {

    $(".js-example-theme-multiple").select2({
    theme: "classic"
    });});
    </script>


{# ----------------------------------- ADD ETAPE --------------------------------------------------- #}
    <div id='container_form' class='ma-classe'>
        <form method="post" enctype="multipart/form-data" class='popupEtape'>
            <div class='popUP_Create Edit-mode '>
                <div class='col-lg-3 Create Edit-mode '> 
                    {# Icon add #}
                    <i class="fa-regular fa-square-plus fa-5x changeColor"></i>
                </div>

                <div class='d-flex align-items-center'>
                    {# titre Create de la pop up ajouter #}
                    <h4>UPDATE ETAPE</h4>
                </div>  
            </div>
            {# <div>
                <h5 class='text-center mt-4 mb-4 text_Size'>Recette <span class="form-contro text_color" >{{ recettes.reLibelle }}</span></h5>
            </div> #}

            <div class='d-flex col-12 mt-2'>
                <div class='col-lg-6'>
                    <div class='p-0' >
                        <div>
                            <label for="{{ form.et_numero.vars.id }}" class="form-contro">Numero de l'étape*</label>
                            {{ form_widget(form.et_numero, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                </div>

                <div class='col-lg-6'>
                    <div class='p-0' >
                        <div>
                            <label for="{{ form.cuisson.vars.id }}" class="form-contro">Mode de cuisson</label>
                            {{ form_widget(form.cuisson, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                </div>
            </div>


            <div class='d-flex col-12 mt-2' >
                <div class='col-lg-12' >
                    <label for="{{ form.et_description.vars.id }}" class="form-contro">Description de l'étape*</label>
                    {{ form_widget(form.et_description, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>

            <div class='SubmitRecettes'> 
                {# Boutton Submit pour soumettre la nouvelle Etape #}
                {# <a class="m-2 btn  myBoutton affichePopUp" href={{url('recette_update', {'id': recettes.id})}}>Retour</a> #}
                {{ form_widget(form.submit , {'attr': {'class': 'btn myBouttonSubmit_Edit  m-2'}}) }}
            </div>

            {{ form_rest(form, {'attr': {'class': 'd-none'}}) }}
        </form>
    </div> 

    <script>
        console.log("Avant l'ajout de la classe");
window.onload = function() {  
    var element = document.querySelector('.ma-classe'); 
  console.log("Élément trouvé :", element);

  if (element) {
    document.body.classList.add('scroll-desactive');
    $('.voile').toggle(); 
    console.log("Classe ajoutée");
  } else {
    console.log("Élément avec la classe spécifique non trouvé");
  }
};
console.log("Après l'écouteur d'événements");    </script>

    </script>
    {% endblock %}