src/Entity/Regions.php
<?php

namespace App\Entity;

use App\Repository\RegionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: RegionsRepository::class)]
#[UniqueEntity(fields: ['reg_libelle'], message: 'Une région avec ce nom existe déjà.')]
class Regions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $reg_libelle = null;

    #[ORM\OneToMany(mappedBy: 'regions', targetEntity: Recettes::class)]
    private Collection $recettes;

    public function __construct()
    {
        $this->recettes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRegLibelle(): ?string
    {
        return $this->reg_libelle;
    }

    public function setRegLibelle(string $reg_libelle): static
    {
        $this->reg_libelle = $reg_libelle;

        return $this;
    }

    /**
     * @return Collection<int, Recettes>
     */
    public function getRecettes(): Collection
    {
        return $this->recettes;
    }

    public function addRecette(Recettes $recette): static
    {
        if (!$this->recettes->contains($recette)) {
            $this->recettes->add($recette);
            $recette->setRegions($this);
        }

        return $this;
    }

    public function removeRecette(Recettes $recette): static
    {
        if ($this->recettes->removeElement($recette)) {
            // set the owning side to null (unless already changed)
            if ($recette->getRegions() === $this) {
                $recette->setRegions(null);
            }
        }

        return $this;
    }
}

src/Form/RegionsType.php
<?php

namespace App\Form;

use App\Entity\Regions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reg_libelle' , TextType::class, [ 
                'label' => 'Titre de la région :  '  ,
                'label_attr' => ['class' => 'form-label'],
                'attr' => [
                    'placeholder' => 'Insérer une région'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Valider',
                'attr' => ['class' => 'btn']
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Regions::class,
        ]);
    }
}

src/Controller/RegionsController.php
<?php

namespace App\Controller;

use App\Entity\Regions;
use App\Form\RegionsType;
use App\Repository\RegionsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RegionsController extends AbstractController
{
    // *********************************************************************************************************************
    //************** GESTION DES REGIONS *******************//
    // *********************************************************************************************************************
    #[Route('/Gestion_Regions', name: 'Gestion_Regions')]
    public function Index(RegionsRepository $repo, Request $request, EntityManagerInterface $manager): Response
    {
        $regions = $repo->findAllSortedByName();
        $isRegionUsed = [];

        foreach ($regions as $region) {
            $isRegionUsed[$region->getId()] = $repo->isRegionUsed($region->getId());
        }
        $region = new Regions();
        $form = $this->createForm(RegionsType::class, $region);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $region = $form->getData();
            $manager->persist($region);
            $manager->flush();
            return $this->redirectToRoute('Gestion_Regions');
        }

        return $this->render('regions/Gestion_regions.html.twig', [
            'regions' => $regions,
            'message' => 'Gestion des régions',
            'isRegionUsed' => $isRegionUsed,
        ]);
    }

    // *********************************************************************************************************************
    //************** AFFICHAGE DU TABLEAU *******************//
    // *********************************************************************************************************************
    #[Route('/Display_List_Regions', name: 'Display_List_Regions')]
    public function Display_List_Regions(RegionsRepository $repo): Response
    {
        $regions = $repo->findAllSortedByName();
        $isRegionUsed = [];

        foreach ($regions as $region) {
            $isRegionUsed[$region->getId()] = $repo->isRegionUsed($region->getId());
        }

        return $this->render('regions/Dipslay_List_Regions.html.twig', [
            'regions' => $regions,
            'isRegionUsed' => $isRegionUsed,
        ]);
    }

    // *********************************************************************************************************************
    //************** CREATE  *******************//
    // *********************************************************************************************************************
    #[Route('/Create_Region', name: 'Create_Region')]
    public function Create_Region(RegionsRepository $repo, Request $request): Response
    {
        $region = new Regions();
        $regions = $repo->findAllSortedByName();
        $form = $this->createForm(RegionsType::class, $region);

        if ($request->isXmlHttpRequest()) { 
            return new Response($this->renderView('regions/Create_Region.html.twig', [
                'form' => $form->createView(),
                'regions' => $regions,    
            ]));
        } 
        return $this->render('regions/Create_Region.html.twig', [
            'form' => $form->createView(),
            'regions' => $regions,
        ]);
    }

    // *********************************************************************************************************************
    //*************** UPDATE *******************//
    // *********************************************************************************************************************
    #[Route('/update_regions/{id}', name: 'update_regions')]
    public function Update_Region(RegionsRepository $repo, Request $request, EntityManagerInterface $manager, $id = null): Response
    {
        $region = $repo->find($id);
        $form = $this->createForm(RegionsType::class, $region);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $region = $form->getData();
            $manager->persist($region);
            $manager->flush();
            return $this->redirectToRoute('Gestion_Regions');
        }
        if ($request->isXmlHttpRequest()) { // Vérifiez si la demande est une requête AJAX
            return new Response($this->renderView('regions/Update_Region.html.twig', [
                'form' => $form->createView(),
                'region' => $region,
            ]));
        } 

        return $this->render('regions/Update_Region.html.twig', [
            'regions' => $region,
            'form' => $form,
        ]);
    }

    // *********************************************************************************************************************
    //*************** DELETE *******************//
    // *********************************************************************************************************************
    #[Route('/delete_region/{id}', name: 'delete_region')]
    public function Delete_Region(Regions $reg,Request $request, EntityManagerInterface $manager): Response
    {
        if ($request->isXmlHttpRequest()) {
            return new Response($this->renderView('regions/Delete_Region.html.twig', [
                'region' => $reg,
            ]));
        } 

        $manager->remove($reg);
        $manager->flush();
        return $this->redirectToRoute('Gestion_Regions');
    }



}

templates/regions/Create_Region.html.twig
{# --------------------------------------POPUP ADD ------------------------------ #}
{% block body %}
        {# Pop Up formulaire #}
        <div class="modal modale fade" id="createRegion"  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createRegionLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header popUP_Create add-mode">
                        {# Icon add #}
                        <i class="fa-regular fa-square-plus fa-3x changeColor"></i>
                        {# titre #}
                        <h5 class="modal-title" id="cuissonLabel"> CREATE RÉGION</h5>
                        {# Btn close #}
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {# Pop Up formulaire Ajouter #}
                    <form method="post" enctype="multipart/form-data" id='createRegion'>
                        <div class='row m-0 justify-content-center mt-3 '>
                            <div class='col-lg-8 p-0'>
                                <div class='col-lg-6'>
                                    {# Label et input #}
                                    <label for="{{ form.reg_libelle.vars.id }}" class="form-contro">Titre de la région</label>
                                    {{ form_widget(form.reg_libelle, {'attr': {'class': 'form-control form-control'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class='SubmitRecettes'>
                            {# bouton retour pour sortir de la popUp #}
                            <button type="button" class="btn myBoutton text-white" data-bs-dismiss="modal">Fermer</button>
                            {# Boutton Submit #}
                            {{ form_widget(form.submit , {'attr': {'class': 'btn  myBouttonSubmit m-2'}}) }}
                        </div>

                        {{ form_rest(form) }}
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

templates/regions/Delete_Region.html.twig
{# --------------------------------------POPUP DELETE ------------------------------ #}
{% block body %}
	{# Pop Up formulaire #}
	<div class="modal fade" id="DeleteRegion{{ region.id }}"  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="DeleteRegionLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header popUP_Create Delete-mode">
					{# Icon Supprimer #}
					<i class="fa-solid fa-trash-can fa-3x changeColor mb-1"></i>
					{# titre Delete #}
					<h5 class="modal-title" id="cuissonLabel"> DELETE RÉGION</h5>
					{# Btn close #}
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="main_delete">
					<p>Suppression de la région
						<span class='text_color_Delete'>{{ region.reglibelle}}</span>
					</p>
				</div>

				<div class='SubmitRecettes'>
					<a class="m-2 btn  myBoutton affichePopUp" href={{url('Gestion_Unites')}}>Retour</a>
					<a class="btn myBouttonSubmit_Delete m-2" href={{url('delete_region', {'id': region.id} )}}>Supprimer</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/regions/Dipslay_List_Regions.html.twig
{% if regions | length > 0 %}
    <div id="dataTables_Container" class="col m-3">
        <table id="dtValues" class="table table-striped" style="width:100%">
            <thead class='pt-2'>
                <tr>
                    <th class="custom-thead custom-Thead">Nom régions</th>
                    <th class="custom-thead custom-THead">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for region in regions %}
                    <tr>
                        <td>{{ region.regLibelle }}</td>
                        <td>
                            <button onclick="showModalUpdateRegion('{{ region.id }}')" class='Btn'><i class="fa-solid fa-pen-to-square text-warning fa-lg"></i></button>                            
                            {% if not isRegionUsed[region.id] %}
                            <button onclick="showModalDeleteRegion('{{ region.id }}')" class='Btn'><i class="fa-solid fa-trash-can text-danger fa-lg"></i></button>                            
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p>Aucun régions pour l'instant</p>
{% endif %} 

templates/regions/Gestion_Regions.html.twig
{# ***************************************** LAYOUT ******************************* #}

{% extends 'backOffice.html.twig' %}

{# ***************************************** TITLE **************************************** #}

{% block title %}Gestion des Régions{% endblock %}

{# ***************************************** NAV ET MENU ********************************** #}

{% block menu %}
    {% include 'Menu.html.twig' %}
{% endblock %}

{# ***************************************** BODY ***************************************** #}

{% block body %}
    {# titre #}
    <h3 class='text-center'>{{message}}</h3>
    <div class="containerPopUP"></div>

{# ------------------------------- BOUTON ADD ------------------------- #}
    {# Boutton ajouter #}
    <button data-bs-toggle="modal" onclick='showModalCreateRegion()' class='Cercle btn'><i class="fa-solid fa-plus-minus text-white fa-2x"></i></button>

    <section class='Container_Table'></section>

<script>
    // Affiche le tableau
    $(document).ready(function() {
        function showDisplay_list_Regions() {
            $.ajax({
                url: '{{ path('Display_List_Regions') }}',
                type: 'GET',
                success: function(response) {
                    $('.Container_Table').html(response);
                    $('#dtValues').DataTable({
                        "stateSave": true,
                        "responsive": true,
                        "language": { "url": "https://cdn.datatables.net/plug-ins/1.12.1/i18n/fr-FR.json" },
                        "pageLength": 4,
                    });                },
                error: function(request, error) {
                    console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
                }
            });
        }

        showDisplay_list_Regions();
    });

    // Affiche la modal create
    function showModalCreateRegion() {
        $.ajax({
            url: '{{ path('Create_Region') }}',
            type: 'GET',
            success: function(html) {
                $('.containerPopUP').html(html);
                $('#createRegion').modal('show');
            },
            error: function(request, error) {
                console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
            }
        });
    }

    // Affiche la modal Update
    function showModalUpdateRegion(id) {
        const url = "{{ path('update_regions', {'id': 'ID_PLACEHOLDER'}) }}".replace('ID_PLACEHOLDER', id);
        $.ajax({
            url: url,
            type: 'GET',
            success: function(html) {
                $('.containerPopUP').html(html);
                $('#updateRegions' + id).modal('show');
            },
            error: function(request, error) {
                console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
            }
        });
    }

    // Affiche la modal delete
    function showModalDeleteRegion(id) {
        const url = "{{ path('delete_region', {'id': 'ID_PLACEHOLDER'}) }}".replace('ID_PLACEHOLDER', id);
        $.ajax({
            url: url,
            type: 'GET',
            success: function(html) {
                $('.containerPopUP').html(html);
                $('#DeleteRegion' + id).modal('show');
            },
            error: function(request, error) {
                console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
            }
        });
    }
</script>
{% endblock %}

templates/regions/Update_Region.html.twig
{# --------------------------------------POPUP UPDATE ------------------------------ #}
{% block body %}
        {# Pop Up formulaire #}
        <div class="modal fade" id="updateRegions{{ region.id }}"  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="updateRegionsLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content j">
                    <div class="modal-header popUP_Create Edit-mode">
                        {# Icon update #}
                        <i class="fa-solid fa-pen-to-square fa-3x changeColor"></i>
                        {# titre update #}
                        <h5 class="modal-title" id="cuissonLabel"> UPDATE RÉGIONS</h5>
                        {# Btn close #}
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {# Pop Up formulaire update #}
                    <form method="post" enctype="multipart/form-data" id='updateRegions{{ region.id }}' action="{{path('update_regions' , { id : region.id })}}">
                        <div class='row m-0 justify-content-center mt-3 '>
                            <div class='col-lg-8 p-0'>
                                <div class='col-lg-6'>
                                    {# Label et input #}
                                    <label for="{{ form.reg_libelle.vars.id }}" class="form-contro">Titre de la région</label>
                                    {{ form_widget(form.reg_libelle, {'attr': {'class': 'form-control form-control'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class='SubmitRecettes'>
                            {# bouton retour pour sortir de la popUp #}
                            <button type="button" class="btn myBoutton text-white" data-bs-dismiss="modal">Fermer</button>
                            {# Boutton Submit #}
                            {{ form_widget(form.submit , {'attr': {'class': 'btn  myBouttonSubmit_Edit m-2'}}) }}
                        </div>

                        {{ form_rest(form) }}
                    </form>
                </div>
            </div>
        </div>
{% endblock %}