src/Entity/Unites.php
<?php

namespace App\Entity;

use App\Repository\UnitesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: UnitesRepository::class)]
#[UniqueEntity(fields: ['un_libelle'], message: 'Une unitée de mesure avec ce nom existe déjà.')]

class Unites
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $un_libelle = null;

    #[ORM\OneToMany(mappedBy: 'unites', targetEntity: Quantites::class)]
    private Collection $quantites;

    public function __construct()
    {
        $this->quantites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUnLibelle(): ?string
    {
        return $this->un_libelle;
    }

    public function setUnLibelle(string $un_libelle): static
    {
        $this->un_libelle = $un_libelle;

        return $this;
    }

    /**
     * @return Collection<int, Quantites>
     */
    public function getQuantites(): Collection
    {
        return $this->quantites;
    }

    public function addQuantite(Quantites $quantite): static
    {
        if (!$this->quantites->contains($quantite)) {
            $this->quantites->add($quantite);
            $quantite->setUnites($this);
        }

        return $this;
    }

    public function removeQuantite(Quantites $quantite): static
    {
        if ($this->quantites->removeElement($quantite)) {
            // set the owning side to null (unless already changed)
            if ($quantite->getUnites() === $this) {
                $quantite->setUnites(null);
            }
        }

        return $this;
    }
}

src/Form/UnitesType.php
<?php

namespace App\Form;

use App\Entity\Unites;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UnitesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('un_libelle', TextType::class, [ 
            'label' => 'Titre de l\'unuité de mesure :',
            'label_attr' => ['class' => 'form-label'],
            'attr' => [
                'placeholder' => 'Insérer une unité'
            ]
        ])
        ->add('submit', SubmitType::class, [
            'label' => 'Valider',
            'attr' => ['class' => 'btn']
        ]);
}

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Unites::class,
        ]);
    }
}

src/Controller/UnitesController.php
<?php

namespace App\Controller;

use App\Entity\Unites;
use App\Form\UnitesType;
use App\Repository\UnitesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UnitesController extends AbstractController
{
    // *********************************************************************************************************************
    //************** GESTION DES UNITES *******************//
    // *********************************************************************************************************************
    #[Route('/Gestion_Unites', name: 'Gestion_Unites')]
    public function Index(UnitesRepository $repo,Request $request, EntityManagerInterface $manager): Response
    {
        $unites = $repo->findAllSortedByName();
        $isInitesUsed = [];

        $unite = new Unites();
        $form = $this->createForm(UnitesType::class, $unite);

        foreach ($unites as $Unite) {
            $isInitesUsed[$Unite->getId()] = $repo->isInitesUsed($Unite->getId());
        }
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $unite = $form->getData();
            $manager->persist($unite);
            $manager->flush();
            return $this->redirectToRoute('Gestion_Unites');
        }
    

        return $this->render('unites/Gestion_Unites.html.twig', [
            'unites' => $unites,
            'form' => $form->createView(),
            'unite' => $unite,
            'message' => 'Gestion des Unités',
            'isInitesUsed' => $isInitesUsed,
        ]);
    }

    // *********************************************************************************************************************
    //************** AFFICHAGE DU TABLEAU *******************//
    // *********************************************************************************************************************
    #[Route('/Display_List_Unites', name: 'Display_List_Unites')]
    public function Display_List_Unites(UnitesRepository $repo): Response
    {
        $unites = $repo->findAllSortedByName();
        $isInitesUsed = [];

        foreach ($unites as $Unite) {
            $isInitesUsed[$Unite->getId()] = $repo->isInitesUsed($Unite->getId());
        }

        return $this->render('unites/Display_List_Unite.html.twig', [
            'unites' => $unites,
            'isInitesUsed' => $isInitesUsed,
        ]);
    }

    // *********************************************************************************************************************
    //************** CREATE  *******************//
    // *********************************************************************************************************************

    #[Route('/Create_Unite', name: 'Create_Unite')]
    public function Create_Unite(UnitesRepository $repo, Request $request, EntityManagerInterface $manager): Response
    {
        $unite = new Unites();
        $unites = $repo->findAllSortedByName();
        $form = $this->createForm(UnitesType::class, $unite);

        if ($request->isXmlHttpRequest()) { 
            return new Response($this->renderView('unites/Create_Unites.html.twig', [
                'form' => $form->createView(),
                'unites' => $unites,    
            ]));
        } 
    }

    // *********************************************************************************************************************
    //*************** UPDATE *******************//
    // *********************************************************************************************************************

    #[Route('/Update_Unite/{id}', name: 'Update_Unite')]
    public function Update_Unite(UnitesRepository $repo, Request $request, EntityManagerInterface $manager, $id = null): Response
    {
        $unite = $repo->find($id);
        $form = $this->createForm(UnitesType::class, $unite);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($unite);
            $manager->flush();
            return $this->redirectToRoute('Gestion_Unites');
        }
        if ($request->isXmlHttpRequest()) {
            return new Response($this->renderView('unites/Update_Unites.html.twig', [
                'form' => $form->createView(),
                'unite' => $unite,
            ]));
        } 
    }

    // *********************************************************************************************************************
    //*************** DELETE *******************//
    // *********************************************************************************************************************
    #[Route('/delete_Unite/{id}', name: 'delete_Unite')]
    public function Delete_Unite(Unites $unite,Request $request, EntityManagerInterface $manager): Response
    {
        if ($request->isXmlHttpRequest()) {
            return new Response($this->renderView('unites/Delete_Unite.html.twig', [
                'unite' => $unite,
            ]));
        } 

        $manager->remove($unite);
        $manager->flush();
        return $this->redirectToRoute('Gestion_Unites');
    }

}

templates/unites/Create_Unites.html.twig
{# --------------------------------------POPUP ADD ------------------------------ #}
{% block body %}
        {# Pop Up formulaire #}
        <div class="modal fade" id="createUnite"  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createUniteLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header popUP_Create add-mode">
                        {# Icon add #}
                        <i class="fa-regular fa-square-plus fa-3x changeColor"></i>
                        {# titre #}
                        <h5 class="modal-title" id="cuissonLabel"> CREATE UNITÉ</h5>
                        {# Btn close #}
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {# Pop Up formulaire Ajouter #}
                    <form method="post" enctype="multipart/form-data" id='createUnite'>
                        <div class='row m-0 justify-content-center mt-3 '>
                            <div class='col-lg-8 p-0'>
                                <div class='col-lg-6'>
                                    {# Label et input #}
                                    <label for="{{ form.un_libelle.vars.id }}" class="form-contro">Titre de l'unité de mesure</label>
                                    {{ form_widget(form.un_libelle, {'attr': {'class': 'form-control form-control'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class='SubmitRecettes'>
                            {# bouton retour pour sortir de la popUp #}
                            <button type="button" class="btn myBoutton text-white" data-bs-dismiss="modal">Fermer</button>
                            {# Boutton Submit #}
                            {{ form_widget(form.submit , {'attr': {'class': 'btn  myBouttonSubmit m-2'}}) }}
                        </div>

                        {{ form_rest(form) }}
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

templates/unites/Delete_Unite.html.twig
{# --------------------------------------POPUP DELETE ------------------------------ #}
	{% block body %}
        {# Pop Up formulaire #}
        <div class="modal fade" id="DeleteUnite{{ unite.id }}"  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="DeleteUniteLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header popUP_Create Delete-mode">
						{# Icon Supprimer #}
						<i class="fa-solid fa-trash-can fa-3x changeColor mb-1"></i>
                        {# titre Delete #}
                        <h5 class="modal-title" id="cuissonLabel"> DELETE UNITÉ</h5>
                        {# Btn close #}
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
					<div class="main_delete">
						<p>Suppression de l'unité
							<span class='text_color_Delete'>{{ unite.unlibelle}}</span>
						</p>
					</div>

					<div class='SubmitRecettes'>
						<a class="m-2 btn  myBoutton affichePopUp" href={{url('Gestion_Unites')}}>Retour</a>
						<a class="btn myBouttonSubmit_Delete m-2" href={{url('delete_Unite', {'id': unite.id} )}}>Supprimer</a>
					</div>
                </div>
            </div>
        </div>
{% endblock %}

templates/unites/Display_List_Unite.html.twig
{% if unites | length > 0 %}
    <div id="dataTables_Container" class="col m-3">
        <table id="dtValues" class="table table-striped" style="width:100%">
            <thead class='pt-2'>
                <tr>
                    <th class="custom-thead custom-Thead">Nom Unité de mesure</th>
                    <th class="custom-thead custom-THead">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for unite in unites %}
                    <tr>
                        <td>{{ unite.unLibelle }}</td>
                        <td>
                            <button onclick="showModalUpdateUnite('{{ unite.id }}')" class='Btn m-1'><i class="fa-solid fa-pen-to-square text-warning fa-lg"></i></button>                            
                            {% if not isInitesUsed[unite.id] %}
                            <button onclick="showModalDeleteUnite('{{ unite.id }}')" class='Btn m-1'><i class="fa-solid fa-trash-can text-danger fa-lg"></i></button>                            
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p>Aucun Unités pour l'instant</p>
{% endif %} 

templates/unites/Gestion_Unites.html.twig
{# ***************************************** FICHIER PARENT ******************************* #}

{% extends 'backOffice.html.twig' %}

{# ***************************************** TITLE **************************************** #}

{% block title %}Gestion des Unités{% endblock %}

{# ***************************************** NAV ET MENU ********************************** #}

{% block menu %}
    {% include 'Menu.html.twig' %}
{% endblock %}

{# ***************************************** BODY ***************************************** #}

{% block body %}
    {# titre #}
    <h3 class='text-center'>{{message}}</h3>
    <div class="containerPopUP"></div>

    {# ------------------------------- BOUTON ADD ------------------------- #}
    {# Boutton ajouter #}
    <button data-bs-toggle="modal" onclick='showModalCreateUnite()' class='Cercle btn'><i class="fa-solid fa-plus-minus text-white fa-2x"></i></button>

    <section class='Container_Table'></section>

<script>
    // Affiche le tableau
    $(document).ready(function() {
        function showDisplay_list_Unites() {
            $.ajax({
                url: '{{ path('Display_List_Unites') }}',
                type: 'GET',
                success: function(response) {
                    $('.Container_Table').html(response);
                    $('#dtValues').DataTable({
                        "stateSave": true,
                        "responsive": true,
                        "language": { "url": "https://cdn.datatables.net/plug-ins/1.12.1/i18n/fr-FR.json" },
                        "pageLength": 4,
                    });                },
                error: function(request, error) {
                    console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
                }
            });
        }

        showDisplay_list_Unites();
    });

    // Affiche la modal create
    function showModalCreateUnite() {
        $.ajax({
            url: '{{ path('Create_Unite') }}',
            type: 'GET',
            success: function (html) {
                $('.containerPopUP').html(html);
                $('#createUnite').modal('show');
            },
            error: function (request, error) {
                console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
            }
        });
    }

    // Affiche la modal Update
    function showModalUpdateUnite(id) {
        const url = "{{ path('Update_Unite', {'id': 'ID_PLACEHOLDER'}) }}".replace('ID_PLACEHOLDER', id);
        $.ajax({
            url: url,
            type: 'GET',
            success: function (html) {
                $('.containerPopUP').html(html);
                $('#updateUnite' + id).modal('show');
            },
            error: function (request, error) {
                console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
            }
        });
    }

    // Affiche la modal delete
    function showModalDeleteUnite(id) {
        const url = "{{ path('delete_Unite', {'id': 'ID_PLACEHOLDER'}) }}".replace('ID_PLACEHOLDER', id);
        $.ajax({
            url: url,
            type: 'GET',
            success: function (html) {
                $('.containerPopUP').html(html);
                $('#DeleteUnite' + id).modal('show');
            },
            error: function (request, error) {
                console.error("Request: " + JSON.stringify(request) + ", Error: " + error);
            }
        });
    }
</script>
{% endblock %}

templates/unites/Update_Unites.html.twig
{# --------------------------------------POPUP UPDATE ------------------------------ #}
{% block body %}
        {# Pop Up formulaire #}
        <div class="modal fade" id="updateUnite{{ unite.id }}"  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="updateUniteLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content j">
                    <div class="modal-header popUP_Create Edit-mode">
                        {# Icon update #}
                        <i class="fa-solid fa-pen-to-square fa-3x changeColor"></i>
                        {# titre update #}
                        <h5 class="modal-title" id="cuissonLabel"> UPDATE UNITÉ</h5>
                        {# Btn close #}
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {# Pop Up formulaire update #}
                    <form method="post" enctype="multipart/form-data" id='updateUnite{{ unite.id }}' action="{{path('Update_Unite' , { id : unite.id })}}">
                        <div class='row m-0 justify-content-center mt-3 '>
                            <div class='col-lg-8 p-0'>
                                <div class='col-lg-6'>
                                    {# Label et input #}
                                    <label for="{{ form.un_libelle.vars.id }}" class="form-contro">Titre de l'unité de mesure</label>
                                    {{ form_widget(form.un_libelle, {'attr': {'class': 'form-control form-control'}}) }}
                                </div>
                            </div>
                        </div>

                        <div class='SubmitRecettes'>
                            {# bouton retour pour sortir de la popUp #}
                            <button type="button" class="btn myBoutton text-white" data-bs-dismiss="modal">Fermer</button>
                            {# Boutton Submit #}
                            {{ form_widget(form.submit , {'attr': {'class': 'btn  myBouttonSubmit_Edit m-2'}}) }}
                        </div>

                        {{ form_rest(form) }}
                    </form>
                </div>
            </div>
        </div>
{% endblock %}